import Vue from 'vue'
import { Button, Container, Header, Main, Aside, Menu, MenuItem, MenuItemGroup, Submenu, Col, Row, Select, Option, Input, Table, TableColumn, Pagination, Card, DatePicker } from 'element-ui'

Vue.use(Button)
    .use(Container)
    .use(Header)
    .use(Aside)
    .use(Main)
    .use(Menu)
    .use(MenuItem)
    .use(MenuItemGroup)
    .use(Submenu)
    .use(Col)
    .use(Row)
    .use(Select)
    .use(Option)
    .use(Input)
    .use(Table)
    .use(TableColumn)
    .use(Pagination)
    .use(Card)
    .use(DatePicker)